apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-webpage
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to My Web Page</title>
    </head>
    <body>
    <h1>Hello, Kubernetes!</h1>
    <p>This is a simple web page served by Nginx!</p>
    </body>
    </html>
