apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        app: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: True
        - name: webpage-volume  # Добавляем этот volumeMount
          mountPath: /usr/share/nginx/html
          readOnly: True
      - name: multitool
        image: praqma/network-multitool
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: webpage-volume  # Добавляем этот volume
        configMap:
          name: nginx-webpage
