apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Опционально, можно указать конкретный NodePort или оставить его выбор Kubernetes
  type: NodePort
